minimumReleaseAge: 10080 # 7 days
blockExoticSubdeps: true # no git branch as package url
resolutionMode: highest

allowBuilds:
  esbuild: true
  lightningcss: true

supportedArchitectures:
  cpu:
    - arm64
    - x64
  os:
    - darwin
    - linux
    - win32
