/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ButtonWithAriaPressedAttributeIndexRouteImport } from './routes/button-with-aria-pressed-attribute/index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ButtonWithAriaPressedAttributeIndexRoute =
  ButtonWithAriaPressedAttributeIndexRouteImport.update({
    id: '/button-with-aria-pressed-attribute/',
    path: '/button-with-aria-pressed-attribute/',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/button-with-aria-pressed-attribute/': typeof ButtonWithAriaPressedAttributeIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/button-with-aria-pressed-attribute': typeof ButtonWithAriaPressedAttributeIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/button-with-aria-pressed-attribute/': typeof ButtonWithAriaPressedAttributeIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/button-with-aria-pressed-attribute/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/button-with-aria-pressed-attribute'
  id: '__root__' | '/' | '/button-with-aria-pressed-attribute/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ButtonWithAriaPressedAttributeIndexRoute: typeof ButtonWithAriaPressedAttributeIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/button-with-aria-pressed-attribute/': {
      id: '/button-with-aria-pressed-attribute/'
      path: '/button-with-aria-pressed-attribute'
      fullPath: '/button-with-aria-pressed-attribute/'
      preLoaderRoute: typeof ButtonWithAriaPressedAttributeIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ButtonWithAriaPressedAttributeIndexRoute:
    ButtonWithAriaPressedAttributeIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
